"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { previewLimits, shiftDay, summarize, type Snapshot } from "../lib/metrics/core";
import { PersonalSummary } from "./personal-summary";
import type { OnboardingAnswers } from "../lib/onboarding";

const usd = (cents: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(cents / 100);
const delta = (current: number, prior: number) => prior === 0 ? `${current} now; 0 previously` : `${Math.abs(Math.round((current - prior) / prior * 100))}% ${current >= prior ? "more" : "fewer"}`;

export function PrivateDashboard({ name, snapshot, demo = false, answers, emailVerified = true }: { name: string; snapshot: Snapshot; demo?: boolean; answers?: OnboardingAnswers; emailVerified?: boolean }) {
  const router = useRouter();
  const [from, setFrom] = useState(snapshot.from), [to, setTo] = useState(snapshot.through.slice(0,10));
  const [deposit, setDeposit] = useState(""), [stake, setStake] = useState(""), [days, setDays] = useState("");
  const [showAll, setShowAll] = useState(false);
  const valid = from >= snapshot.from && to <= snapshot.through.slice(0,10) && from <= to;
  const m = useMemo(() => valid ? summarize(snapshot, from, to) : null, [snapshot, from, to, valid]);
  const limit = (s: string, cents = true) => s.trim() === "" || !Number.isFinite(Number(s)) || Number(s) < 0 ? null : Math.round(Number(s) * (cents ? 100 : 1));
  const limits = m ? previewLimits(m, limit(deposit), limit(stake), limit(days,false)) : null;
  const hasInvalidLimit = [deposit,stake,days].some(s => s !== "" && (!Number.isFinite(Number(s)) || Number(s) < 0)) || (days !== "" && !Number.isInteger(Number(days)));
  function lastDays(n: number) { const end = snapshot.through.slice(0,10); setTo(end); setFrom([snapshot.from,shiftDay(end,1-n)].sort().at(-1)!); }
  return <>
    <div className="private-nav"><a href="/" className="brand"><span>◒</span> stillwater</a><div className="private-nav-right"><span className="private-label">{demo ? "Demo preview" : "Betting tracker"}</span>{demo && <a href="/sign-in">Sign in</a>}</div></div>
    <main className="private-dashboard metrics-dashboard">
      <section className="welcome-row"><div><p className="eyebrow">Awareness, at your pace</p><h1>{demo ? "Make room for a different habit." : `Hi, ${name}.`}</h1><p className="intro">Understand the money and attention going into gambling. Choose what you want to change.</p></div></section>
      {!demo && answers && <PersonalSummary answers={answers} emailVerified={emailVerified} />}
      <section className="connection-card"><div><strong>DraftKings · Synthetic demo</strong><p>Sample activity from a supplied fixture, not your account data. No live sportsbook connection.</p><small>Activity through {snapshot.through.slice(0,10)} · Loaded {new Date(snapshot.loadedAt).toLocaleString("en-US",{timeZone:"UTC"})} UTC</small></div><button className="outline-button" onClick={() => router.refresh()}>Reload demo</button></section>
      <section className="metrics-filters" aria-label="Activity date range"><label>From<input type="date" min={snapshot.from} max={snapshot.through.slice(0,10)} value={from} onChange={e => setFrom(e.target.value)} /></label><label>Through<input type="date" min={snapshot.from} max={snapshot.through.slice(0,10)} value={to} onChange={e => setTo(e.target.value)} /></label><button onClick={() => lastDays(14)}>Last 14 data days</button><button onClick={() => lastDays(30)}>Last 30 data days</button><button onClick={() => {setFrom(snapshot.from);setTo(snapshot.through.slice(0,10));}}>All history</button><small>All dates use UTC. Filters end at the dataset, not today.</small></section>
      {!m || !limits ? <p role="alert">Choose a valid date range within {snapshot.from}–{snapshot.through.slice(0,10)}.</p> : <>
        <section className="metric-grid"><Metric label="Cash wagered" value={usd(m.cashWagered)} detail="Cash put into bets placed in this period" /><Metric label="Bets placed" value={String(m.betCount)} detail={`${m.activeDays} betting days out of ${m.days}`} /><Metric label="Days without recorded bets" value={String(m.daysWithoutBets)} detail="Within this synthetic demo history only" /><Metric label="Settled betting result" value={usd(m.settledResult)} detail={`${m.settledCount} bets settled in this period; returns + refunds − cash stakes`} /></section>
        <p className="metrics-note">A positive result does not mean gambling is harmless. Frequency, amounts, and your own commitments matter independently of wins and losses.</p>
        <section className="dashboard-grid"><article className="panel"><p className="eyebrow">Financial picture</p><h2>Follow the cash</h2><dl className="metric-details"><Row name="Deposits" value={usd(m.deposits)} /><Row name="Withdrawals" value={usd(m.withdrawals)} /><Row name="Net deposits" value={usd(m.netDeposits)} /><Row name="Cash payouts" value={usd(m.payouts)} /><Row name="Cash refunds" value={usd(m.refunds)} /><Row name="Cash betting flow" value={usd(m.cashBettingFlow)} /><Row name="Opening cash balance" value={usd(m.opening)} /><Row name="Closing cash balance" value={usd(m.closing)} /><Row name="Bonus stakes placed" value={usd(m.bonusWagered)} /></dl><p className="fineprint">Net deposits = deposits − withdrawals. Cash betting flow = payouts + refunds − cash wagers recorded in the period. Opening balance + net deposits + cash betting flow = closing balance. It can differ from settled results while bets remain open or settle across date boundaries.</p><p className="fineprint">At period end: {m.openCount} unsettled bets with {usd(m.openCashStake)} cash committed. Stakes may be wagered again after a return; total stakes are not unique money deposited.</p></article>
        <article className="panel"><p className="eyebrow">Frequency & exposure</p><h2>Notice your activity</h2><dl className="metric-details"><Row name="Average cash stake per bet" value={m.averageStake === null ? "Unavailable" : usd(m.averageStake)} /><Row name="Largest cash stake" value={m.maxStake === null ? "Unavailable" : usd(m.maxStake)} /><Row name="Longest stretch without recorded bets" value={`${m.longestBreak} days`} /><Row name="Time in gambling apps" value="Unavailable" /></dl><p className="fineprint">The average includes bonus-only bets with $0 cash stake. Days without bets describe this provider’s records, not verified abstinence across other apps. Time between bets is not screen time.</p><h3>Compared with the preceding period</h3>{m.comparison ? <><p>{delta(m.betCount,m.comparison.bets)} bets ({m.betCount} vs {m.comparison.bets}). Cash wagered: {usd(m.cashWagered)} vs {usd(m.comparison.cashStake)}. Betting days: {m.activeDays} vs {m.comparison.activeDays}.</p><p className="fineprint">Equal {m.days}-day windows; previous period {m.comparison.from}–{m.comparison.to}. These are descriptive changes, not an ML risk score or a psychological assessment.</p></> : <p className="fineprint">Not enough earlier history for an equal-length comparison. Try the last 14 data days.</p>}</article></section>
        <section className="panel daily-panel"><p className="eyebrow">Daily activity</p><h2>When gambling shows up</h2><p>Cash wagered by day. Hover or focus a bar for the amount and number of bets.</p><div className="daily-bars" role="group" aria-label="Daily cash wagers">{m.daily.map(d => <div tabIndex={0} className="daily-column" key={d.date} title={`${d.date}: ${usd(d.cashStake)}, ${d.count} bets`} aria-label={`${d.date}: ${usd(d.cashStake)}, ${d.count} bets`}><div style={{height:`${Math.max(2, d.cashStake / Math.max(1,...m.daily.map(x=>x.cashStake))*130)}px`, background: d.count ? "#547768" : "#d7ddd5"}} /></div>)}</div><div className="date-ends"><span>{m.from}</span><span>{m.to}</span></div><details><summary>View daily amounts as a table</summary><div className="metrics-table-scroll"><table><thead><tr><th>Date (UTC)</th><th>Bets</th><th>Cash wagered</th><th>Deposits</th></tr></thead><tbody>{m.daily.map(d=><tr key={d.date}><td>{d.date}</td><td>{d.count}</td><td>{usd(d.cashStake)}</td><td>{usd(d.deposits)}</td></tr>)}</tbody></table></div></details></section>
        <section className="panel guardrail-panel"><p className="eyebrow">Choose what you want to change</p><h2>Try a guardrail against this history</h2><p>Explore reducing deposits, smaller cash stakes, or fewer betting days. Set a limit to 0 to preview a stopping goal.</p><div className="guardrail-fields"><label>Deposit cap for selected period ($)<input type="number" min="0" step="0.01" value={deposit} placeholder="No cap selected" onChange={e=>setDeposit(e.target.value)}/></label><label>Maximum cash stake per bet ($)<input type="number" min="0" step="0.01" value={stake} placeholder="No cap selected" onChange={e=>setStake(e.target.value)}/></label><label>Maximum betting days in period<input type="number" min="0" step="1" value={days} placeholder="No cap selected" onChange={e=>setDays(e.target.value)}/></label></div><div aria-live="polite">{hasInvalidLimit ? <p role="alert">Use nonnegative limits and a whole number of betting days.</p> : <><p>{limits.depositExceeded === null ? "Choose a deposit cap to compare." : `Deposits ${limits.depositExceeded ? "exceeded" : "stayed within"} this proposed cap: ${usd(m.deposits)} of ${usd(limit(deposit)!)}.`}</p><p>{limits.betsOverLimit === null ? "Choose a cash stake cap to compare." : `${limits.betsOverLimit} of ${m.betCount} bets exceeded this proposed cash stake cap.`}</p><p>{limits.activeDaysExceeded === null ? "Choose a betting-day cap to compare." : `${m.activeDays} betting days; proposed cap ${days}. ${limits.activeDaysExceeded ? "Above" : "Within"} this cap.`}</p></>}</div><p className="fineprint">Historical preview only. These entries are not saved, do not block gambling, and do not notify anyone. Changing the date range changes the period being evaluated. A cash-only stake limit does not capture bonus-only betting; a zero betting-day goal does.</p></section>
        <section className="panel activity-panel"><div className="panel-title"><div><p className="eyebrow">Source activity</p><h2>Transactions</h2></div><button className="text-link" onClick={()=>setShowAll(!showAll)}>{showAll ? "Show recent" : `View all ${m.recent.length}`}</button></div>{!m.recent.length && <p>No transactions in this period.</p>}{m.recent.slice(0,showAll?undefined:8).map(t=><div className="activity-row" key={t.id}><div><strong>{t.type.replaceAll("_"," ")}</strong><small>{t.description}</small></div><time>{t.at.slice(0,16).replace("T"," ")} UTC</time><b>{usd(t.cash)}{t.bonus !== 0 && <small>{usd(t.bonus)} bonus</small>}</b></div>)}</section>
      </>}
    </main>
  </>;
}
function Metric({label,value,detail}:{label:string;value:string;detail:string}) { return <article className="private-metric"><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>; }
function Row({name,value}:{name:string;value:string}) { return <div><dt>{name}</dt><dd>{value}</dd></div>; }
